@startuml Activity_Attestation
title Аттестация сотрудника

|HR|
start
:Подготовить материалы аттестации;

|Сотрудник|
:Пройти тестирование;

fork
  :Заполнить анкету;
fork again
  :Выполнить кейс-задание;
end fork

|Руководитель|
:Провести собеседование;

if (Результат положительный?) then (Да)
  |HR|
  :Обновить матрицу компетенций;
  stop "Готов к повышению"
else (Нет)
  :Уведомление о снижении выплат;
  :Предупреждение об увольнении;
  stop "Отправлен на дообучение"
endif

@enduml
